# Generated by Django 3.2.13 on 2022-05-10 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('channel_name', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Nombre del canal')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('chat_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='Id del chat')),
                ('unread_msn', models.PositiveSmallIntegerField(default=0, help_text='Número de mensajes no leidos.')),
                ('last_msn', models.CharField(blank=True, max_length=50, null=True)),
                ('chat_name', models.CharField(max_length=20)),
                ('time', models.PositiveIntegerField(blank=True, help_text='timestamp', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado.', verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='modified at')),
            ],
            options={
                'ordering': ['-modified', '-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=128, null=True)),
                ('file', models.FileField(upload_to='files/')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado.', verbose_name='Creado en')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Id del mensaje')),
                ('body', models.TextField(blank=True, max_length=4096, null=True)),
                ('from_me', models.BooleanField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.PositiveIntegerField(blank=True, help_text='timestamp', null=True)),
                ('type_message', models.CharField(blank=True, max_length=16, null=True, verbose_name='Tipo de mensaje')),
                ('sender_name', models.CharField(blank=True, help_text='Nombre de quien envía el mensaje.', max_length=64, null=True)),
                ('caption', models.CharField(blank=True, help_text='Subtítulo de un mensaje cuando es de galería.', max_length=128, null=True)),
                ('quoted_msg_body', models.CharField(blank=True, help_text='Cuerpo del mensaje al cual se está respondiendo', max_length=128, null=True)),
                ('quoted_msg_type', models.CharField(blank=True, help_text='Tipo de mensaje al cual se está respondiendo.', max_length=16, null=True)),
                ('state', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Estado del mensaje: 1-Enviado, 2-Entregado, 3-Leido', null=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='chatwp.conversation')),
            ],
        ),
    ]
